version: "3.5"

networks:
  net_lb:
    external: true

services:
  webcams:
    image: 871800672816.dkr.ecr.us-east-1.amazonaws.com/mercadopago:latest
    restart: unless-stopped
    hostname: mercadopago
    env_file: .env
    ports:
      - "8000"
    networks:
      - net_lb
    entrypoint:
      - /app_conf/services/web.sh
    volumes:
      - /etc/localtime:/etc/localtime
      - ./shared-volume/media:/code/media
      - ./db.sqlite3:/code/db.sqlite3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mercadopago.rule=Host(`mercadopago.hugoseabra.space`)"
      - "traefik.http.routers.mercadopago.entrypoints=web"
      - "traefik.protocol=http"
      - "traefik.docker.network=net_lb"
      - "traefik.frontend.passHostHeader=true"
